language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
install:
  - pip install pytest
  - pip install coveralls
script:
  coverage run --source=mf2util runtests.py
after_success:
  coveralls
sudo: false
